"""Deny-by-default backend capabilities for the static MCP service principal.

The service key authenticates a non-human workload. Authentication never grants
blanket administrator authority: every backend route used by the sidecar has an
explicit verdict here, keyed by HTTP method and FastAPI route template. Unknown
routes are denied. Human JWT administrators do not pass through this matrix.
"""

from __future__ import annotations


# Complete MCP endpoint-contract inventory. Entries stay here even when refused
# so adding a tool contract requires an explicit backend authority decision.
_MCP_DECLARED_ROUTES: frozenset[tuple[str, str]] = frozenset({
    ('DELETE', '/api/backup/saved/{filename}'),
    ('DELETE', '/api/channel-groups/orphaned'),
    ('DELETE', '/api/channel-groups/{group_id}'),
    ('DELETE', '/api/channel-pipeline/rules/{rule_id}'),
    ('DELETE', '/api/channels/logos/{logo_id}'),
    ('DELETE', '/api/channels/{channel_id}'),
    ('DELETE', '/api/cloud-targets/{target_id}'),
    ('DELETE', '/api/dummy-epg/profiles/{profile_id}'),
    ('DELETE', '/api/epg/sources/{source_id}'),
    ('DELETE', '/api/epg/sources/{source_id}/sd-lineups'),
    ('DELETE', '/api/event-sync-exclusions/{exclusion_id}'),
    ('DELETE', '/api/m3u/accounts/{account_id}'),
    ('DELETE', '/api/normalization/groups/{group_id}'),
    ('DELETE', '/api/normalization/rules/{rule_id}'),
    ('DELETE', '/api/notifications'),
    ('DELETE', '/api/sync-targets/{target_id}'),
    ('DELETE', '/api/tags/groups/{group_id}'),
    ('DELETE', '/api/tags/groups/{group_id}/tags/{tag_id}'),
    ('DELETE', '/api/tasks/{task_id}/schedules/{schedule_id}'),
    ('GET', '/api/alert-methods'),
    ('GET', '/api/backup/create'),
    ('GET', '/api/backup/export-sections'),
    ('GET', '/api/backup/saved'),
    ('GET', '/api/backup/saved/{filename}'),
    ('GET', '/api/channel-groups'),
    ('GET', '/api/channel-groups/auto-created'),
    ('GET', '/api/channel-groups/hidden'),
    ('GET', '/api/channel-groups/orphaned'),
    ('GET', '/api/channel-groups/with-streams'),
    ('GET', '/api/channel-merges'),
    ('GET', '/api/channel-merges/candidates'),
    ('GET', '/api/channel-pipeline/circuit-breaker'),
    ('GET', '/api/channel-pipeline/executions'),
    ('GET', '/api/channel-pipeline/executions/{execution_id}'),
    ('GET', '/api/channel-pipeline/executions/{execution_id}/snapshot'),
    ('GET', '/api/channel-pipeline/fuzzy-preview'),
    ('GET', '/api/channel-pipeline/rules'),
    ('GET', '/api/channel-pipeline/rules/{rule_id}'),
    ('GET', '/api/channel-profiles'),
    ('GET', '/api/channels'),
    ('GET', '/api/channels/logos'),
    ('GET', '/api/channels/logos/{logo_id}'),
    ('GET', '/api/channels/{channel_id}'),
    ('GET', '/api/channels/{channel_id}/streams'),
    ('GET', '/api/cloud-targets'),
    ('GET', '/api/dummy-epg/profiles'),
    ('GET', '/api/dummy-epg/profiles/{profile_id}'),
    ('GET', '/api/epg/audit-duplicates'),
    ('GET', '/api/epg/grid'),
    ('GET', '/api/epg/sources'),
    ('GET', '/api/epg/sources/{source_id}/sd-lineups'),
    ('GET', '/api/event-sync-exclusions'),
    ('GET', '/api/event-sync/team-aliases'),
    ('GET', '/api/journal'),
    ('GET', '/api/m3u/accounts/{account_id}'),
    ('GET', '/api/m3u/digest/settings'),
    ('GET', '/api/normalization/groups'),
    ('GET', '/api/normalization/groups/{group_id}'),
    ('GET', '/api/normalization/rules'),
    ('GET', '/api/normalization/rules/{rule_id}'),
    ('GET', '/api/notifications'),
    ('GET', '/api/providers'),
    ('GET', '/api/settings'),
    ('GET', '/api/stats/activity'),
    ('GET', '/api/stats/bandwidth'),
    ('GET', '/api/stats/channel-bandwidth'),
    ('GET', '/api/stats/channels'),
    ('GET', '/api/stats/popularity/channel/{channel_id}'),
    ('GET', '/api/stats/popularity/rankings'),
    ('GET', '/api/stats/popularity/trending'),
    ('GET', '/api/stats/providers/bitrate'),
    ('GET', '/api/stats/providers/buffering'),
    ('GET', '/api/stats/providers/channel-heatmap'),
    ('GET', '/api/stats/providers/stream-usage'),
    ('GET', '/api/stats/providers/watch-time'),
    ('GET', '/api/stats/top-watched'),
    ('GET', '/api/stats/unique-viewers'),
    ('GET', '/api/stats/unique-viewers-by-channel'),
    ('GET', '/api/stats/users/dispatcharr/{user_id}'),
    ('GET', '/api/stats/users/emby/{emby_user_id}'),
    ('GET', '/api/stats/watch-history'),
    ('GET', '/api/stats/watch-time'),
    ('GET', '/api/stream-profiles'),
    ('GET', '/api/stream-stats/dismissed'),
    ('GET', '/api/stream-stats/probe/history'),
    ('GET', '/api/stream-stats/probe/progress'),
    ('GET', '/api/stream-stats/probe/results'),
    ('GET', '/api/stream-stats/stale'),
    ('GET', '/api/stream-stats/struck-out'),
    ('GET', '/api/stream-stats/summary'),
    ('GET', '/api/streams'),
    ('GET', '/api/streams/stale-ids'),
    ('GET', '/api/sync-targets'),
    ('GET', '/api/sync-targets/{target_id}'),
    ('GET', '/api/tags/groups'),
    ('GET', '/api/tags/groups/{group_id}'),
    ('GET', '/api/tasks'),
    ('GET', '/api/tasks/history/all'),
    ('GET', '/api/tasks/{task_id}/history'),
    ('GET', '/api/tasks/{task_id}/schedules'),
    ('PATCH', '/api/channel-profiles/{profile_id}/channels/bulk-update'),
    ('PATCH', '/api/channels/logos/{logo_id}'),
    ('PATCH', '/api/channels/{channel_id}'),
    ('PATCH', '/api/cloud-targets/{target_id}'),
    ('PATCH', '/api/dummy-epg/profiles/{profile_id}'),
    ('PATCH', '/api/epg/sources/{source_id}'),
    ('PATCH', '/api/m3u/accounts/{account_id}'),
    ('PATCH', '/api/normalization/groups/{group_id}'),
    ('PATCH', '/api/normalization/rules/{rule_id}'),
    ('PATCH', '/api/notifications/mark-all-read'),
    ('PATCH', '/api/tags/groups/{group_id}'),
    ('PATCH', '/api/tags/groups/{group_id}/tags/{tag_id}'),
    ('POST', '/api/alert-methods/{method_id}/test'),
    ('POST', '/api/auto-creation/run/commit'),
    ('POST', '/api/auto-creation/run/prepare'),
    ('POST', '/api/backup/restore-dbas-saved'),
    ('POST', '/api/backup/restore-saved'),
    ('POST', '/api/backup/save'),
    ('POST', '/api/channel-groups'),
    ('POST', '/api/channel-merges'),
    ('POST', '/api/channel-merges/{merge_id}/accept'),
    ('POST', '/api/channel-merges/{merge_id}/dismiss'),
    ('POST', '/api/channel-pipeline/run/commit'),
    ('POST', '/api/channel-pipeline/run/prepare'),
    ('POST', '/api/channel-pipeline/event-sync-preview'),
    ('POST', '/api/channel-pipeline/executions/{execution_id}/restore-snapshot'),
    ('POST', '/api/channel-pipeline/executions/{execution_id}/rollback'),
    ('POST', '/api/channel-pipeline/reset-circuit-breaker'),
    ('POST', '/api/channel-pipeline/rules'),
    ('POST', '/api/channel-pipeline/rules/analyze'),
    ('POST', '/api/channel-pipeline/rules/{rule_id}/duplicate'),
    ('POST', '/api/channel-pipeline/rules/{rule_id}/toggle'),
    ('POST', '/api/channel-pipeline/run'),
    ('POST', '/api/channels'),
    ('POST', '/api/channels/assign-numbers'),
    ('POST', '/api/channels/bulk-commit'),
    ('POST', '/api/channels/bulk-merge'),
    ('POST', '/api/channels/clear-auto-created'),
    ('POST', '/api/channels/find-duplicates'),
    ('POST', '/api/channels/logos'),
    ('POST', '/api/channels/preview-csv'),
    ('POST', '/api/channels/{channel_id}/add-stream'),
    ('POST', '/api/channels/{channel_id}/add-streams'),
    ('POST', '/api/channels/{channel_id}/remove-stream'),
    ('POST', '/api/channels/{channel_id}/reorder-streams'),
    ('POST', '/api/cloud-targets'),
    ('POST', '/api/cloud-targets/test'),
    ('POST', '/api/cloud-targets/{target_id}/test'),
    ('POST', '/api/dummy-epg/generate'),
    ('POST', '/api/dummy-epg/preview'),
    ('POST', '/api/dummy-epg/profiles'),
    ('POST', '/api/emby/clear-logos'),
    ('POST', '/api/emby/clear-logos/prepare'),
    ('POST', '/api/epg/channels/{channel_id}/link'),
    ('POST', '/api/epg/match'),
    ('POST', '/api/epg/sources'),
    ('POST', '/api/epg/sources/{source_id}/refresh'),
    ('POST', '/api/epg/sources/{source_id}/sd-lineups'),
    ('POST', '/api/epg/sources/{source_id}/sd-lineups/search'),
    ('POST', '/api/event-sync-exclusions'),
    ('POST', '/api/m3u/accounts'),
    ('POST', '/api/m3u/refresh'),
    ('POST', '/api/m3u/refresh/{account_id}'),
    ('POST', '/api/normalization/apply-to-channels'),
    ('POST', '/api/normalization/groups'),
    ('POST', '/api/normalization/rules'),
    ('POST', '/api/normalization/test-batch'),
    ('POST', '/api/stream-stats/compute-sort'),
    ('POST', '/api/stream-stats/dismiss'),
    ('POST', '/api/stream-stats/probe/all'),
    ('POST', '/api/stream-stats/probe/bulk'),
    ('POST', '/api/stream-stats/probe/cancel'),
    ('POST', '/api/stream-stats/probe/reset'),
    ('POST', '/api/stream-stats/probe/{stream_id}'),
    ('POST', '/api/stream-stats/struck-out/remove'),
    ('POST', '/api/streams/by-ids'),
    ('POST', '/api/sync-targets'),
    ('POST', '/api/tags/groups'),
    ('POST', '/api/tags/groups/{group_id}/tags'),
    ('POST', '/api/tags/test'),
    ('POST', '/api/tasks/{task_id}/cancel'),
    ('POST', '/api/tasks/{task_id}/run'),
    ('POST', '/api/tasks/{task_id}/schedules'),
    ('PUT', '/api/channel-pipeline/rules/{rule_id}'),
    ('PUT', '/api/event-sync/team-aliases'),
    ('PUT', '/api/m3u/digest/settings'),
    ('PUT', '/api/sync-targets/{target_id}'),
    # Contract-exempt multipart/text and composed MCP calls.
    ("GET", "/api/channels/export-csv"),
    ("POST", "/api/channels/import-csv"),
    ("GET", "/api/channels/bulk-commit/{job_id}"),
    ("GET", "/api/emby/clear-logos/{job_id}"),
    ("GET", "/api/epg/data/{data_id}"),
    ("POST", "/api/channel-pipeline/rules/analyze/from-bundle"),
    ("PATCH", "/api/m3u/accounts/{account_id}/group-settings"),
    # Full settings round-trip used by M3U group-auto-sync tooling. The
    # settings handler independently strips/refuses admin-only fields for the
    # MCP principal; admitting this route does not grant credential writes.
    ("POST", "/api/settings"),
})


# Capabilities reserved to a human administrator. This is intentionally
# broader than the current sidecar contract: identity, service-key and TLS
# routes remain classified if a future tool tries to call them.
MCP_HUMAN_ONLY_ROUTES: frozenset[tuple[str, str]] = frozenset({
    # MCP pipeline execution is exposed only through the content-bound
    # prepare/commit pair. Humans retain the legacy one-shot route.
    ("POST", "/api/channel-pipeline/run"),
    # Credential-bearing backup export/restore and destructive restore.
    ("GET", "/api/backup/create"),
    ("POST", "/api/backup/save"),
    ("GET", "/api/backup/saved"),
    ("GET", "/api/backup/saved/{filename}"),
    ("DELETE", "/api/backup/saved/{filename}"),
    ("POST", "/api/backup/restore-saved"),
    ("POST", "/api/backup/restore-dbas-saved"),
    ("POST", "/api/backup/restore"),
    ("POST", "/api/backup/restore-yaml"),
    ("POST", "/api/backup/restore-dbas"),
    # Outbound destinations and credentials: reads remain masked and allowed;
    # activation, credential replacement, creation and deletion are human-only.
    ("POST", "/api/cloud-targets"),
    ("PATCH", "/api/cloud-targets/{target_id}"),
    ("DELETE", "/api/cloud-targets/{target_id}"),
    ("POST", "/api/cloud-targets/test"),
    ("POST", "/api/cloud-targets/{target_id}/test"),
    ("POST", "/api/sync-targets"),
    ("PUT", "/api/sync-targets/{target_id}"),
    ("DELETE", "/api/sync-targets/{target_id}"),
    ("POST", "/api/epg/sources"),
    ("PATCH", "/api/epg/sources/{source_id}"),
    ("DELETE", "/api/epg/sources/{source_id}"),
    ("POST", "/api/epg/sources/{source_id}/sd-lineups"),
    ("DELETE", "/api/epg/sources/{source_id}/sd-lineups"),
    ("POST", "/api/epg/sources/{source_id}/sd-lineups/search"),
    ("POST", "/api/m3u/accounts"),
    ("PATCH", "/api/m3u/accounts/{account_id}"),
    ("DELETE", "/api/m3u/accounts/{account_id}"),
    # Existing outbound credential oracles and alert credential lifecycle.
    ("POST", "/api/alert-methods/{method_id}/test"),
    ("POST", "/api/alert-methods"),
    ("PATCH", "/api/alert-methods/{method_id}"),
    ("DELETE", "/api/alert-methods/{method_id}"),
    # Human identity and authorization administration.
    ("GET", "/api/auth/admin/settings"),
    ("PUT", "/api/auth/admin/settings"),
    ("GET", "/api/auth/admin/users"),
    ("GET", "/api/auth/admin/users/{user_id}"),
    ("PUT", "/api/auth/admin/users/{user_id}"),
    ("DELETE", "/api/auth/admin/users/{user_id}"),
    ("GET", "/api/auth/identities"),
    ("POST", "/api/auth/identities/link"),
    ("DELETE", "/api/auth/identities/{identity_id}"),
    ("PUT", "/api/auth/me"),
    ("POST", "/api/auth/change-password"),
    # Static service-key and TLS/private-key lifecycle.
    ("POST", "/api/settings/mcp-api-key"),
    ("DELETE", "/api/settings/mcp-api-key"),
    ("PATCH", "/api/settings/security"),
    ("GET", "/api/tls/settings"),
    ("POST", "/api/tls/configure"),
    ("POST", "/api/tls/request-cert"),
    ("POST", "/api/tls/complete-challenge"),
    ("POST", "/api/tls/upload-cert"),
    ("POST", "/api/tls/renew"),
    ("POST", "/api/tls/https/start"),
    ("POST", "/api/tls/https/stop"),
    ("POST", "/api/tls/https/restart"),
    ("DELETE", "/api/tls/certificate"),
    # Human review of contradictory upstream channel-profile settings.
    ("GET", "/api/profile-conflict-reviews"),
    ("POST", "/api/profile-conflict-reviews/{review_id}/accept"),
})

MCP_ALLOWED_ROUTES: frozenset[tuple[str, str]] = (
    _MCP_DECLARED_ROUTES - MCP_HUMAN_ONLY_ROUTES
)


def is_mcp_route_allowed(method: str, route_template: str | None) -> bool:
    """Return the explicit service-principal verdict; unknown means denied."""
    if route_template is None:
        return False
    return (method.upper(), route_template) in MCP_ALLOWED_ROUTES
