"""
Observability baseline — structured JSON logging + Prometheus metrics.

This module provides the three building blocks that give ECM operators an
honest answer to "what just happened?":

1. A trace-id contextvar so every log line within a request shares a single
   correlation key (read from the inbound ``X-Request-ID`` header when
   present, else a fresh UUIDv4 generated by the correlation middleware).

2. A JSON log formatter + stdlib ``logging.Filter`` that binds ``trace_id``
   (plus any ad-hoc context set via :func:`bind_context`) onto every
   :class:`logging.LogRecord`. The result is one line of machine-parseable
   JSON per log event — no grep-and-pray across multi-line tracebacks.

3. Prometheus metrics — counters/histograms for HTTP traffic and gauges for
   the readiness endpoint. The HTTP middleware labels by route *pattern*
   (``/api/channels/{channel_id}``), never raw path, so cardinality stays
   bounded regardless of traffic mix. Readiness sub-checks get a bounded
   ``check`` label that matches the keys returned by the readiness probe.

Conventions (enforced here, documented in ``docs/backend_architecture.md``):

- Metric naming: ``ecm_<subsystem>_<name>_<unit>`` (snake_case, unit suffix).
- Label cardinality: bounded sets only. Never ``user_id``, ``trace_id``,
  or raw paths. Per-request correlation belongs in logs, not metric labels.
- Required log fields: ``ts``, ``level``, ``logger``, ``msg``, ``trace_id``.
  Extra fields flow through ``bind_context`` (e.g. ``restore_id``,
  ``sync_id``, ``phase``).

The :func:`install_observability` function is the single entry point —
``main.py`` calls it once at import time and everything else is wired up.
"""
from __future__ import annotations

import contextvars
import hashlib
import itertools
import json
import logging
import os
import sys
import threading
import time
import uuid
from typing import Any, Callable, Dict, Iterable, Optional

try:  # pragma: no cover — defensive for environments without prometheus-client
    from prometheus_client import (
        CONTENT_TYPE_LATEST,
        CollectorRegistry,
        Counter,
        Gauge,
        Histogram,
        generate_latest,
    )
except ImportError:  # pragma: no cover
    CONTENT_TYPE_LATEST = "text/plain"
    CollectorRegistry = None  # type: ignore[assignment]
    Counter = None  # type: ignore[assignment]
    Gauge = None  # type: ignore[assignment]
    Histogram = None  # type: ignore[assignment]
    generate_latest = None  # type: ignore[assignment]


# =========================================================================
# Trace-id + bound-context plumbing
# =========================================================================
# Why a contextvar? Async request handlers cannot rely on thread-local
# storage — an ``asyncio`` task may hop between threads. A contextvar is
# propagated correctly through ``await`` boundaries and task spawning
# (``asyncio.create_task`` copies the current context), which is exactly the
# semantics the correlation middleware needs.
_trace_id_var: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "ecm_trace_id", default=None
)
_bound_context_var: contextvars.ContextVar[Dict[str, Any]] = contextvars.ContextVar(
    "ecm_bound_context", default={}
)


def get_trace_id() -> Optional[str]:
    """Return the current request's trace id, or ``None`` outside a request."""
    return _trace_id_var.get()


def set_trace_id(trace_id: str) -> contextvars.Token:
    """Set the trace id for the current context. Returns a reset token."""
    return _trace_id_var.set(trace_id)


def reset_trace_id(token: contextvars.Token) -> None:
    """Reset the trace id using a token from :func:`set_trace_id`."""
    _trace_id_var.reset(token)


def bind_context(**fields: Any) -> contextvars.Token:
    """Attach key/value pairs to every log line in the current context.

    Typical use — a long-running restore job binds ``restore_id`` at the top,
    so every log line inside the task carries it without the call sites
    having to thread it through::

        token = bind_context(restore_id=restore.id, phase="validate")
        try:
            run_validation()
        finally:
            reset_context(token)

    The returned token can be passed to :func:`reset_context` to pop the
    binding (e.g. in a ``finally`` clause or a context manager).
    """
    current = dict(_bound_context_var.get())
    current.update(fields)
    return _bound_context_var.set(current)


def reset_context(token: contextvars.Token) -> None:
    """Undo a prior :func:`bind_context` call."""
    _bound_context_var.reset(token)


def generate_trace_id() -> str:
    """Return a fresh UUIDv4 string suitable for use as a trace id."""
    return str(uuid.uuid4())


# =========================================================================
# JSON logging
# =========================================================================
class _TraceIdFilter(logging.Filter):
    """Attach ``trace_id`` and any bound context to each log record.

    Runs as a filter (not a formatter) so the metadata is available to any
    formatter the operator plugs in downstream — including the JSON
    formatter we install below and any custom handlers that might want to
    consume structured attributes directly.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        record.trace_id = _trace_id_var.get() or "-"
        bound = _bound_context_var.get()
        if bound:
            for key, value in bound.items():
                # Don't let bound context clobber reserved LogRecord attrs
                # (``message``, ``asctime``, etc.) — namespace-collide defensively.
                if not hasattr(record, key):
                    setattr(record, key, value)
        return True


# Fields we already represent explicitly in the JSON payload — skip them in
# the generic "extra" sweep so we don't double-emit.
_STANDARD_LOGRECORD_FIELDS = frozenset(
    {
        "name", "msg", "args", "levelname", "levelno", "pathname", "filename",
        "module", "exc_info", "exc_text", "stack_info", "lineno", "funcName",
        "created", "msecs", "relativeCreated", "thread", "threadName",
        "processName", "process", "message", "asctime", "taskName",
    }
)


class JsonFormatter(logging.Formatter):
    """Emit each log record as a single-line JSON document.

    Required fields — ``ts``, ``level``, ``logger``, ``msg``, ``trace_id`` —
    are always present. Any extra attributes attached to the LogRecord (via
    ``logger.info("...", extra={...})`` or :func:`bind_context`) flow into
    the top-level JSON object so downstream log pipelines can index on them
    without custom parsing.
    """

    def format(self, record: logging.LogRecord) -> str:  # noqa: A003 — stdlib signature
        payload: Dict[str, Any] = {
            "ts": self.formatTime(record, datefmt="%Y-%m-%dT%H:%M:%S") + f".{int(record.msecs):03d}Z",
            "level": record.levelname,
            "logger": record.name,
            "msg": record.getMessage(),
            "trace_id": getattr(record, "trace_id", "-"),
        }
        if record.exc_info:
            payload["exc_info"] = self.formatException(record.exc_info)
        if record.stack_info:
            payload["stack_info"] = self.formatStack(record.stack_info)

        # Sweep in any extra attributes (bound context, explicit extras).
        for key, value in record.__dict__.items():
            if key in _STANDARD_LOGRECORD_FIELDS or key == "trace_id":
                continue
            try:
                json.dumps(value)  # fast check for serializability
                payload[key] = value
            except (TypeError, ValueError):
                payload[key] = repr(value)

        return json.dumps(payload, default=str, separators=(",", ":"))


def install_json_logging(level: int = logging.INFO) -> None:
    """Swap the root logger's handlers for a JSON-emitting stream handler.

    Idempotent — calling twice leaves a single JSON handler in place. The
    ``_TraceIdFilter`` is applied on both the handler and the root logger
    so the trace id survives regardless of whether a subclassed logger adds
    its own handler.
    """
    root = logging.getLogger()
    json_handler = logging.StreamHandler()
    json_handler.setFormatter(JsonFormatter())
    json_handler.addFilter(_TraceIdFilter())

    for existing in list(root.handlers):
        if getattr(existing, "_ecm_json_handler", False):
            # Drop any handler we previously installed (idempotency).
            root.removeHandler(existing)
        elif type(existing) is logging.StreamHandler and getattr(
            existing, "stream", None
        ) in (sys.stderr, sys.stdout):
            # Remove the plain console handler ``logging.basicConfig``
            # installed at import time. Keeping it — even re-formatted to
            # JSON — leaves TWO console handlers on the root logger, so
            # every record is emitted twice (bd-cng0d: duplicate JSON
            # access-log lines). ``type() is`` (not ``isinstance``) so
            # FileHandler and other StreamHandler subclasses are left
            # alone, and the stream check spares handlers a test attached
            # to capture output into a StringIO.
            root.removeHandler(existing)

    json_handler._ecm_json_handler = True  # type: ignore[attr-defined]
    root.addHandler(json_handler)
    root.addFilter(_TraceIdFilter())
    root.setLevel(level)


# =========================================================================
# Prometheus metrics
# =========================================================================
# A dedicated registry keeps ECM metrics isolated from any collectors a
# third-party library might have auto-registered on ``REGISTRY``. Tests can
# build a fresh registry to avoid "Duplicated timeseries in CollectorRegistry"
# errors when re-importing the module.
REGISTRY: Optional[CollectorRegistry] = None
_METRICS: Dict[str, Any] = {}


# Latency histogram buckets — tuned for a local web app hitting SQLite +
# a LAN Dispatcharr instance. Most requests land under 100 ms; the long
# tail past 5 s captures the pathological "something went wrong" cases.
_HTTP_LATENCY_BUCKETS = (
    0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
)
_HEALTH_CHECK_BUCKETS = (
    0.001, 0.005, 0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 3.0,
)

# Normalization runs at microsecond-to-millisecond scale — well below the
# floor of the HTTP buckets. A dedicated histogram shape captures the sub-ms
# distribution that dominates this work's latency profile.
_NORMALIZATION_LATENCY_BUCKETS = (
    0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5,
)


def _build_metrics(registry: CollectorRegistry) -> Dict[str, Any]:
    """Instantiate the ECM metric set against ``registry``."""
    return {
        # ----------------------------------------------------------------
        # Build identity (bd-h0wfu).
        #
        # ``ecm_app_info`` is the canonical Prometheus "info" pattern — a
        # gauge stuck at 1.0 whose ONLY purpose is to carry build-identity
        # labels (``version``, ``git_sha``, ``release_channel``). Operators
        # use it to answer "what is the running container actually built
        # from?" without having to parse JSON from /api/health, which is a
        # recurring source of fake "test failure" beads where the real
        # cause is container drift from origin/dev.
        #
        # Cardinality: bounded — each running container has exactly one
        # (version, git_sha, release_channel) tuple for its lifetime. A
        # fresh container build produces a single new time series.
        # ``install_metrics`` sets the gauge to 1.0 with the labels read
        # from the build-time environment (GIT_COMMIT, ECM_VERSION,
        # RELEASE_CHANNEL — all baked into the image by Dockerfile ARGs).
        # ----------------------------------------------------------------
        "app_info": Gauge(
            "ecm_app_info",
            "Build identity of the running container. Labels carry the "
            "version, git SHA, and release channel baked in at image-build "
            "time. Value is always 1.0 — query the labels, not the value.",
            ["version", "git_sha", "release_channel"],
            registry=registry,
        ),
        "http_requests_total": Counter(
            "ecm_http_requests_total",
            "Count of HTTP requests processed, labeled by method, route "
            "pattern, and response status code.",
            ["method", "path", "status"],
            registry=registry,
        ),
        "http_request_duration_seconds": Histogram(
            "ecm_http_request_duration_seconds",
            "HTTP request latency in seconds, labeled by method and route "
            "pattern. Buckets cover sub-10ms up to 10s outliers.",
            ["method", "path"],
            buckets=_HTTP_LATENCY_BUCKETS,
            registry=registry,
        ),
        "health_ready_ok": Gauge(
            "ecm_health_ready_ok",
            "1 when /api/health/ready reports all subsystems healthy, else 0. "
            "Last evaluated value — the readiness endpoint updates this on each call.",
            registry=registry,
        ),
        "health_ready_check_duration_seconds": Histogram(
            "ecm_health_ready_check_duration_seconds",
            "Duration of each readiness sub-check (database, dispatcharr, ffprobe).",
            ["check"],
            buckets=_HEALTH_CHECK_BUCKETS,
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Normalization observability (bd-eio04.9).
        #
        # ``rule_matches_total`` labels by ``rule_category`` — a bounded
        # enum drawn from the NormalizationRule action_type namespace
        # (``remove``, ``replace``, ``regex_replace``, ``strip_prefix``,
        # ``strip_suffix``, ``normalize_prefix``, ``capitalize``,
        # ``tag_group``, ``legacy_tag``, ``other``). Per-rule-id breakdown
        # is NOT a metric label (cardinality bomb — there is no upper
        # bound on user-created rules) — it goes in the sampled INFO log
        # instead, per PO decision 6 (hybrid metric + log).
        #
        # ``auto_creation_channels_created_total`` labels by
        # ``normalized`` ∈ {true, false, skipped} (three fixed values).
        # "skipped" is emitted when no normalization groups were
        # configured for the rule — important signal that distinguishes
        # "ran and did nothing" from "never ran at all".
        #
        # ``canary_divergence_total`` has no labels. This is the SLI
        # numerator for SLO-5 (Normalization Correctness) — any non-zero
        # rate over the measurement window is an SLO breach.
        # ----------------------------------------------------------------
        "normalization_rule_matches_total": Counter(
            "ecm_normalization_rule_matches_total",
            "Count of normalization rule matches by rule category. "
            "rule_category is a bounded enum mapped from NormalizationRule.action_type; "
            "per-rule-id detail lives in the sampled INFO log.",
            ["rule_category"],
            registry=registry,
        ),
        "normalization_no_change_total": Counter(
            "ecm_normalization_no_change_total",
            "Count of normalize() invocations where the output matched the "
            "input verbatim (ran but produced no change).",
            registry=registry,
        ),
        "auto_creation_channels_created_total": Counter(
            "ecm_auto_creation_channels_created_total",
            "Count of auto-created channels, labeled by whether normalization "
            "was applied. 'true' = ran and changed name. 'false' = ran and "
            "produced no change. 'skipped' = no normalization groups configured.",
            ["normalized"],
            registry=registry,
        ),
        "normalization_duration_seconds": Histogram(
            "ecm_normalization_duration_seconds",
            "Duration of a single normalize() call, in seconds. Buckets cover "
            "the sub-millisecond regime typical for this work.",
            buckets=_NORMALIZATION_LATENCY_BUCKETS,
            registry=registry,
        ),
        "normalization_canary_divergence_total": Counter(
            "ecm_normalization_canary_divergence_total",
            "Count of nightly canary divergences between Test Rules (test_rule / "
            "test_rules_batch) and auto-creation executor output. "
            "SLI numerator for SLO-5 — any non-zero rate over the window is a breach.",
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Interactive stream dedup (ADR-008, BD-F / bd-a5lb2).
        #
        # ``pending_merges_queue_depth_added_total`` is the LOCKED CONTRACT
        # counter per BD-M (``docs/sre/slos.md`` SLI-10b denominator and
        # the ``ECMDedupPendingMergeResolutionStale`` alert rule). One
        # increment per row inserted into the ``pending_merges`` queue —
        # currently emitted only by BD-F's bulk-M3U-import hook; BD-D
        # (candidate lookup) and BD-E (operator drag-drop / add-stream /
        # MCP enqueue) will also emit it as those land.
        #
        # Label-free: per-source attribution belongs in structured logs
        # (``[DEDUP] Enqueued pending merge … trigger=m3u_refresh``), NOT
        # in the metric. ADR-008 §D6's ``trigger_context`` enum has four
        # values; pushing them through a label would create a cardinality
        # contract this metric does not commit to.
        #
        # The companion gauge ``ecm_pending_merges_queue_depth`` (below) is
        # NOT in the BD-M locked contract — gauge maintenance landed as a
        # separate bead (bd-wvr1d) so BD-F was not blocked on the
        # cross-cutting plumbing required to keep a gauge in sync across
        # all four trigger surfaces + the operator-resolution paths.
        # ----------------------------------------------------------------
        "pending_merges_queue_depth_added_total": Counter(
            "ecm_pending_merges_queue_depth_added_total",
            "Count of rows inserted into the pending_merges queue by the "
            "interactive stream-dedup epic (ADR-008). One increment per "
            "fresh insert; partial-unique-index collisions (ADR-008 §D5) "
            "do not increment. Denominator for SLI-10b "
            "(pending merge resolution rate within 24h) per "
            "docs/sre/slos.md.",
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Companion gauge to the LOCKED CONTRACT counter above (bd-wvr1d).
        #
        # ``pending_merges_queue_depth`` is set to the CURRENT count of
        # ``pending_merges`` rows with ``status='pending'`` after every
        # transition that changes the queue depth:
        #
        #   * BD-F insert (fresh row added)              → set after commit
        #   * BD-E accept (row flipped to 'merged')      → set after commit
        #   * BD-E dismiss (row flipped to 'dismissed')  → set after commit
        #   * Startup task                                → seeds on boot
        #
        # IMPORTANT — NOT A LOCKED CONTRACT. The counter
        # ``ecm_pending_merges_queue_depth_added_total`` is the SLI-10b
        # source (docs/sre/slos.md SLO-10). This gauge is a *diagnostic*
        # complement — it answers "how big is the queue right now?" for
        # dashboards and ad-hoc debugging. Alerts and runbooks MUST NOT
        # take a dependency on this gauge without explicit cross-team
        # review, because:
        #
        #   1. Gauge accuracy is best-effort. Every set-site wraps the
        #      COUNT query in a try/except; a DB hiccup or startup race
        #      leaves the gauge stale rather than crashing the write path.
        #   2. The gauge reflects the queue depth *after* the transition
        #      that triggered the set — there is no atomic "flip + read"
        #      guarantee; a concurrent accept/dismiss can race the COUNT.
        #
        # Use the counter for SLI math; use this gauge for dashboards.
        # ----------------------------------------------------------------
        "pending_merges_queue_depth": Gauge(
            "ecm_pending_merges_queue_depth",
            "Current number of pending_merges rows in status='pending'. "
            "Set after every BD-F insert and BD-E accept/dismiss commit, "
            "and seeded on app startup. Diagnostic companion to the LOCKED "
            "CONTRACT counter ecm_pending_merges_queue_depth_added_total — "
            "NOT a contract SLI; see observability.py for dependency "
            "restrictions (bd-wvr1d).",
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Frontend error telemetry (ADR-006, bd-i6a1m).
        #
        # ``client_errors_total`` labels:
        #   kind    — fixed enum {boundary, unhandled_rejection, chunk_load,
        #             resource, other}. Unknown values are collapsed to
        #             "other" by routers/client_errors.py so cardinality is
        #             bounded.
        #   release — short build-env identifier. Cardinality is bounded
        #             by the in-router LRU at 3 real values + "stale" roll-up
        #             (see ADR-006 §9).
        #
        # ``client_errors_dropped_total`` labels:
        #   reason  — fixed enum {rate_limited, oversized, invalid_schema}.
        #             No other values are ever emitted by the router.
        #
        # ``client_error_reports_bytes`` records the post-parse request size
        # so the operator can correlate payload size with reporter bugs.
        # Buckets cover the expected range — most reports are <1 KB, the
        # cap is 8 KB — plus a long tail for pre-scrub oversizes that got
        # accepted anyway (they shouldn't, but we want the signal).
        # ----------------------------------------------------------------
        "client_errors_total": Counter(
            "ecm_client_errors_total",
            "Count of frontend error reports ingested by /api/client-errors, "
            "labeled by kind (fixed enum) and release (bounded LRU).",
            ["kind", "release"],
            registry=registry,
        ),
        "client_errors_dropped_total": Counter(
            "ecm_client_errors_dropped_total",
            "Count of frontend error reports rejected before ingest. reason "
            "∈ {rate_limited, oversized, invalid_schema}.",
            ["reason"],
            registry=registry,
        ),
        "client_error_reports_bytes": Histogram(
            "ecm_client_error_reports_bytes",
            "Size in bytes of accepted /api/client-errors request bodies, "
            "post-parse. Buckets cover sub-kilobyte through the 8 KB cap.",
            buckets=(128, 256, 512, 1024, 2048, 4096, 8192),
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Session lifecycle (bd-arp3o, spike bd-1tl01).
        #
        # ``session_starts_total`` is the SLO-6 denominator — number of
        # unique frontend sessions that POSTed /api/session-start. The
        # counter has NO labels (per ADR-006 §9 cardinality posture); the
        # session_id itself never becomes a label and is never logged.
        # The router maintains an in-memory dedup set keyed by session_id
        # (TTL=24h) so a hard-refresh inside the same tab cannot
        # double-count a single browser session.
        #
        # ``session_dedup_set_size`` exposes the dedup set's current
        # cardinality so SRE can spot a leaking pruner — a slowly-growing
        # gauge means the lazy reaper has regressed and the in-memory
        # set is accumulating stale entries past their TTL.
        # ----------------------------------------------------------------
        "session_starts_total": Counter(
            "ecm_session_starts_total",
            "Count of unique frontend sessions observed via "
            "POST /api/session-start. SLO-6 SLI denominator. "
            "No labels — session_id is in-memory dedup state, never a label.",
            registry=registry,
        ),
        "session_dedup_set_size": Gauge(
            "ecm_session_dedup_set_size",
            "Current size of the in-memory session-id dedup set. Steady "
            "state ~= sessions seen in the last 24h. A monotonically "
            "growing value indicates the lazy TTL reaper has regressed.",
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Stats v2 observability (bd-skqln.12).
        #
        # The metric set below covers the four observability surfaces the
        # Stats v2 epic requires:
        #
        #   1. session_telemetry write health (success/failure counter,
        #      duration histogram, last-batch row-count gauge)
        #   2. Per-poll provider resolution success rate (the modernized
        #      replacement for the dual-write divergence SLI that the
        #      epic originally specified; skqln.3 step (d) removed the
        #      legacy writer, so the divergence is no longer measurable
        #      — the resolver's resolved-rate is the surviving SLI)
        #   3. Stats v2 HTTP query latency (emitted by the existing
        #      observability middleware in main.py with a filter on
        #      ``/api/stats/*`` paths; gives the SLI surface a clean
        #      handle distinct from generic HTTP traffic)
        #
        # Cardinality posture (SRE veto on user_id / channel_id):
        #
        # * No metric below carries user_id, channel_id, session_id,
        #   target_id, or client_ip as a label. Those identifiers belong
        #   in logs (correlated by trace_id), never in the metric label
        #   space. Even though session_telemetry rows DO record user_id
        #   and channel_id, the metrics aggregate over them.
        # * provider_id IS allowed by SRE pre-clearance (<20 providers
        #   bounded), but NO stats v2 metric below uses it as a label in
        #   this bead. Future provider-keyed metrics belong to follow-up
        #   beads with explicit SRE sign-off.
        # * ``result`` labels are fixed enums: success/failure for write
        #   health, resolved/unresolved for provider resolution. No other
        #   values are ever emitted.
        # * ``endpoint`` uses the FastAPI matched route PATTERN
        #   (``/api/stats/watch-time/{user_id}``), NEVER the resolved
        #   path. ``granularity`` is sourced from the ``group_by`` query
        #   parameter when present (currently ``total`` / ``day``);
        #   defaults to ``"none"`` for endpoints that don't accept a
        #   group-by axis. Combined ceiling is ~5 endpoints × 3
        #   granularities = ~15 series.
        # ----------------------------------------------------------------
        "session_telemetry_writes_total": Counter(
            "ecm_session_telemetry_writes_total",
            "Count of session_telemetry write attempts (one per "
            "BandwidthTracker poll cycle), labeled by outcome. "
            "result ∈ {success, failure}. Failures are wrapped by the "
            "tracker's try/except so the legacy sibling writes that ran "
            "before the helper survive — this counter exposes the "
            "swallowed failure rate so SRE can alert on it.",
            ["result"],
            registry=registry,
        ),
        "session_telemetry_write_duration_seconds": Histogram(
            "ecm_session_telemetry_write_duration_seconds",
            "Wall time of one _write_session_telemetry call, in seconds. "
            "Buckets cover the sub-millisecond regime typical for a "
            "small batch of inserts into a SQLite WAL store, with a long "
            "tail for the pathological 'something is wrong with the "
            "database' case.",
            buckets=_NORMALIZATION_LATENCY_BUCKETS,
            registry=registry,
        ),
        "session_telemetry_row_count": Gauge(
            "ecm_session_telemetry_row_count",
            "Total row count of session_telemetry after the most recent "
            "nightly rollup + prune run. Set by StatsV2RollupTask after "
            "a successful prune step — one update per nightly run. Used "
            "by SRE storage-growth alerts (ECMStatsRowCountGrowthAnomaly). "
            "bd-ae58c (Option B): BandwidthTracker no longer writes this "
            "gauge; per-poll batch size is derivable from the "
            "ecm_session_telemetry_writes_total counter rate.",
            registry=registry,
        ),
        "session_telemetry_rows_excluded_total": Counter(
            "ecm_session_telemetry_rows_excluded_total",
            "Cumulative count of session_telemetry rows that were filtered "
            "OUT before insert, labeled by reason. reason ∈ {excluded_user}. "
            "The ``excluded_user`` reason fires when ECM_TELEMETRY_EXCLUDE_USERS "
            "matches a row's Dispatcharr-side user_id or username (bd-uqbob). "
            "Honest accounting: the rows are skipped, not silently zeroed, so "
            "this counter surfaces 'how many viewers would have shown up that "
            "we deliberately did not record' without leaking the identity of "
            "the excluded user into the metric label space.",
            ["reason"],
            registry=registry,
        ),
        "provider_resolution_total": Counter(
            "ecm_provider_resolution_total",
            "Count of channel-poll provider-resolution outcomes, "
            "labeled by outcome. result ∈ {resolved, unresolved}. The "
            "ratio resolved / (resolved + unresolved) is the bd-skqln.14 "
            "data-consistency SLI — target ≥95% steady state. Increments "
            "ONCE PER CHANNEL per poll cycle, so the rate scales with "
            "active channels, not active sessions.",
            ["result"],
            registry=registry,
        ),
        "stats_query_duration_seconds": Histogram(
            "ecm_stats_query_duration_seconds",
            "Latency of Stats v2 HTTP queries, in seconds. Labels: "
            "endpoint (FastAPI route pattern, e.g. "
            "'/api/stats/watch-time/{user_id}') and granularity "
            "(value of the 'group_by' query param, or 'none' if absent). "
            "Bounded label set: ~5 stats endpoints × 3 granularities. "
            "Emitted by the observability middleware in main.py with a "
            "filter on /api/stats/* paths; non-stats traffic continues "
            "to use the generic ecm_http_request_duration_seconds.",
            ["endpoint", "granularity"],
            buckets=_HTTP_LATENCY_BUCKETS,
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Stats v2 — nightly rollup/prune job (ADR-007 D6, bd-7i2vv).
        #
        # Five metrics emitted by ``tasks.stats_v2_rollup.StatsV2RollupTask``
        # after each nightly run. SRE owns operational behavior (skqln.11
        # alert rules wire on these); this module just publishes them.
        #
        # Cardinality posture:
        #   * No user_id, channel_id, or session_id in labels (SRE veto).
        #   * No provider_id in labels here either — the rollup job
        #     aggregates over providers per run, so the per-run metrics
        #     are label-free. (Future per-provider rollup latency, if it
        #     ever lands, gets its own bead and explicit SRE sign-off.)
        #   * ``rollup_name`` is a bounded enum {user_daily,
        #     provider_daily} — explicit allowlist; new rollups need to
        #     extend the enum in tasks/stats_v2_rollup.py.
        # ----------------------------------------------------------------
        "telemetry_rollup_last_success_timestamp": Gauge(
            "ecm_telemetry_rollup_last_success_timestamp",
            "Unix-epoch seconds of the most recent SUCCESSFUL nightly "
            "rollup run for each named rollup. SRE's staleness alert "
            "wires on (time() - this_gauge): >36h warn (failure mode 1), "
            ">25d page (failure mode 2, raw rows approaching the 30d "
            "prune horizon before being rolled up). Updated by the "
            "rollup task only after the prune step also completed; a "
            "failure during rollup or a guard-fired prune-skip does NOT "
            "advance this gauge. Per-rollup so SRE can distinguish a "
            "stuck user_daily from a stuck provider_daily.",
            ["rollup_name"],
            registry=registry,
        ),
        "telemetry_rollup_duration_seconds": Histogram(
            "ecm_telemetry_rollup_duration_seconds",
            "Wall time of one rollup run for each named rollup, in "
            "seconds. Buckets cover the sub-second case (the rollup "
            "writes <few-thousand rows per day) up to the long tail "
            "where the catch-up budget kicks in and the job is rolling "
            "up many days at once after extended downtime.",
            ["rollup_name"],
            buckets=_HTTP_LATENCY_BUCKETS,
            registry=registry,
        ),
        "telemetry_rollup_days_processed": Gauge(
            "ecm_telemetry_rollup_days_processed",
            "Number of UTC calendar days processed by the most recent "
            "rollup run for each named rollup. Normally 1 (the previous "
            "complete day); higher values indicate a catch-up run after "
            "downtime, which is the leading indicator for failure mode "
            "2 (>25 days uncovered → page).",
            ["rollup_name"],
            registry=registry,
        ),
        "telemetry_raw_rows_pruned": Counter(
            "ecm_telemetry_raw_rows_pruned",
            "Cumulative count of raw session_telemetry rows deleted by "
            "the nightly prune step (ADR-007 D3 step 3). Always-monotonic; "
            "deltas over the alerting window are the rate of pruning. A "
            "sustained zero rate combined with a growing "
            "ecm_session_telemetry_row_count is failure mode 3 (prune "
            "failing silently). The prune step runs only after rollup "
            "succeeded — so a zero rate when rollup is failing is "
            "expected (fail-safe).",
            registry=registry,
        ),
        "telemetry_rollup_errors_total": Counter(
            "ecm_telemetry_rollup_errors_total",
            "Cumulative count of rollup-job error conditions, labeled by "
            "phase. phase ∈ {rollup, prune, marker, sanity_check}. "
            "'sanity_check' increments when a day had source rows but "
            "produced zero rollup rows (failure mode 5 — never prune "
            "what you couldn't roll up). 'rollup' covers SQL/IO failures "
            "during the aggregate INSERT. 'prune' covers DELETE failures. "
            "'marker' covers failures persisting telemetry_rollup_state. "
            "A non-zero rate is the SRE signal that the job has begun "
            "drifting; failure modes 1-2 ride on (time-since-success) "
            "in the gauge above, this counter ride on (rate-of-errors).",
            ["phase"],
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # DBAS scheduled/manual backup outcomes (bead 0i2vt.6).
        #
        # ``ecm_backup_runs_total`` labels by ``result`` — a bounded set:
        #   'success'  the DbasBackupTask built a sealed artifact + sidecar.
        #   'skipped'  the fire-time credential-freshness gate aborted the
        #              run (target missing / disabled / revoked / rotated).
        #              This is a SKIP, not a failure — it is the operator's
        #              own configuration change taking effect, but it is NOT
        #              silent: a WARN log, journal entry and NotificationCenter
        #              notification accompany every increment (a backup that
        #              silently stops = false safety).
        #   'failed'   the artifact build itself raised (disk, IO, gather).
        #
        # SRE: a sustained 'skipped'/'failed' rate with a zero 'success'
        # rate over the alerting window is the #1 op risk for this feature
        # (a scheduled backup that has quietly stopped producing artifacts).
        # Cardinality is fixed at three series.
        "backup_runs_total": Counter(
            "ecm_backup_runs_total",
            "Cumulative count of DBAS backup task runs, labeled by result. "
            "result ∈ {success, skipped, failed}. 'success' = a sealed "
            "artifact + sidecar were written. 'skipped' = the fire-time "
            "credential-freshness gate aborted the run (target missing, "
            "disabled, revoked, or credential rotated) — a non-silent abort "
            "that also emits a WARN log, journal entry and notification. "
            "'failed' = the artifact build itself raised.",
            ["result"],
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # DBAS cloud upload outcomes (bead 0i2vt.8).
        #
        # ``ecm_backup_upload_total`` labels by ``provider`` and ``result``:
        #   provider ∈ {s3, gdrive, webdav} — the three shipping adapters in
        #            v0.18.0 (dropbox/onedrive deferred to v0.18.x). Cardinality
        #            is bounded by the get_adapter() provider_type allowlist.
        #   result   ∈ {success, failed} — one increment per outbound upload of
        #            the sealed artifact (and its .sha256 sidecar) to a
        #            configured+enabled target. A target that is skipped by the
        #            fire-time freshness gate does NOT increment this counter
        #            (it increments ecm_backup_runs_total{result="skipped"} once
        #            for the run, not per-target here).
        #
        # SRE: the ratio failed / (success + failed) is the cloud-upload error
        # SLI for DBAS offsite backups; a sustained non-zero failed rate means
        # backups are being produced locally but not landing offsite — the host
        # is one disk failure away from total backup loss.
        # ----------------------------------------------------------------
        "backup_upload_total": Counter(
            "ecm_backup_upload_total",
            "Cumulative count of DBAS cloud-upload attempts, labeled by "
            "provider (s3|gdrive|webdav) and result (success|failed). One "
            "increment per outbound artifact upload to a configured+enabled "
            "target. Freshness-gate skips are counted on ecm_backup_runs_total "
            "(result=skipped), not here.",
            ["provider", "result"],
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # DBAS cross-instance sync outcomes (bead enhancedchannelmanager-k78ja,
        # epic i39wu).
        #
        # ``ecm_sync_runs_total`` labels by ``result`` — a bounded tri-state set
        # mirroring ``ecm_backup_runs_total``:
        #   'success'  the DbasSyncTask completed a clean run — a dry-run plan
        #              that produced a preview, or an APPLY whose RestoreReport
        #              outcome was SUCCESS. This is also the ONLY result that
        #              stamps ecm_task_schedule_last_success_timestamp (the
        #              task_engine stamps it on TaskResult.success), so a
        #              'success' increment is the heartbeat the staleness alert
        #              keys off.
        #   'partial'  an APPLY whose outcome was mixed / rolled-back (tri-state
        #              discipline — NEVER reported as a clean success). The
        #              per-task success gauge is NOT stamped on a partial, so a
        #              SUSTAINED partial loop ALSO trips ECMSyncStalledTargetDrift
        #              (the staleness clock never resets). That is correct:
        #              target B is drifting either way.
        #   'failed'   the run raised, the freshness gate aborted (target
        #              missing / disabled / revoked / rotated), or no
        #              sync_target_id was configured — every non-clean,
        #              non-partial terminal state. Freshness aborts are
        #              non-silent (WARN + journal + notification) independent of
        #              this counter.
        #
        # SRE: the #1 operator risk for cross-instance sync is SILENT DRIFT —
        # a sync quietly failing (or looping on partial) for N cycles while B
        # diverges from A, discovered only at failover. A sustained
        # 'partial'/'failed' rate with a zero 'success' rate is that signal;
        # the freshness/last-success staleness alert (ECMSyncStalledTargetDrift)
        # is the time-since-success counterpart. Cardinality is fixed at three
        # series.
        #
        # 7ipq2.3 (per-target sync tasks) + PO-authorized follow-on: the
        # counter also carries ``sync_target_id``. Aggregate-only, it could
        # tell an operator that SOMETHING was failing but not WHICH replica —
        # while the freshness gauge had already become per-target, leaving
        # the runbook's triage step reading two signals at different
        # granularities. The label key is the SyncTarget row **pk**, matching
        # ecm_sync_last_full_success_timestamp and the per-target task id:
        # the pk is immutable, so a target rename cannot fork the series and
        # break rate()/increase() continuity the way a name label would.
        # Cardinality stays small and bounded: 3 results x the operator's
        # sync_targets rows (1-3 typical), plus at most one "unknown" series
        # for the no-target-selected failure path.
        # ----------------------------------------------------------------
        "sync_runs_total": Counter(
            "ecm_sync_runs_total",
            "Cumulative count of DBAS cross-instance sync task runs, labeled by "
            "result AND sync_target_id (the SyncTarget row pk — immutable, so a "
            "rename cannot fork the series; 'unknown' only on the no-target-"
            "selected failure path). result ∈ {success, partial, failed}. "
            "'success' = a clean "
            "dry-run plan or an APPLY with a SUCCESS outcome (also the heartbeat "
            "that stamps ecm_task_schedule_last_success_timestamp). 'partial' = "
            "an APPLY with a mixed/rolled-back outcome (target B drifting; "
            "tri-state discipline — never a clean success, and does NOT stamp "
            "the last-success gauge). 'failed' = the run raised, the credential-"
            "freshness gate aborted, or no target was configured.",
            ["result", "sync_target_id"],
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Cross-instance sync FULL-APPLY freshness (PR #752 review, Block 2).
        #
        # ``ecm_task_schedule_last_success_timestamp`` is the GENERIC task
        # health gauge: the task engine stamps it on ANY TaskResult.success,
        # and a dry-run PREVIEW legitimately reports success (it produced a
        # plan without writing B). Keying the drift alert on that gauge let a
        # recurring preview reset the staleness clock while B kept diverging
        # — a silent-drift mask, the exact failure ECMSyncStalledTargetDrift
        # exists to catch.
        #
        # This gauge is stamped ONLY by DbasSyncTask on a run that actually
        # APPLIED and returned a clean SUCCESS outcome (never a dry-run,
        # never a partial/rolled-back apply, never a freshness abort). It is
        # the SLI the alert keys on; the generic gauge stays as-is for
        # "is this task running at all" task-health questions.
        #
        # Labeled by ``sync_target_id`` (the SyncTarget row pk as a string) —
        # per-target attribution so one replica's healthy apply cannot reset
        # another's clock. Cardinality is bounded by the operator's
        # sync_targets rows (1-3 typical), and the values are DB pks from
        # code-controlled call sites, never raw request input.
        # ----------------------------------------------------------------
        "sync_last_full_success_timestamp": Gauge(
            "ecm_sync_last_full_success_timestamp",
            "Unix-epoch seconds of the most recent FULL APPLIED cross-instance "
            "sync (a confirm_apply run whose RestoreReport outcome was SUCCESS), "
            "labeled by sync_target_id. A dry-run preview, a partial/rolled-back "
            "apply, and a credential-freshness abort all leave this UNCHANGED — "
            "unlike the generic ecm_task_schedule_last_success_timestamp, which "
            "the task engine stamps on any successful run including a preview. "
            "This is the freshness SLI behind ECMSyncStalledTargetDrift.",
            ["sync_target_id"],
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Database file size (bd-ygoqr — paired with the CleanupTask CRON
        # default flip; together they give operators "is my DB growing?"
        # signal AND an automatic weekly VACUUM that bounds the growth).
        #
        # Two gauges, no labels — the SQLite database is a single
        # process-global file, so labeling would just inject a constant-
        # cardinality column for no benefit. Update cost is two
        # ``os.path.getsize`` calls per emit point (single syscall each),
        # so the gauges are wired only at points that already do real I/O:
        #
        #   1. ``database._perform_maintenance`` at startup (post-VACUUM).
        #   2. ``CleanupTask.execute`` (post-VACUUM) — the gauge reflects
        #      the freshly-vacuumed file size, not the pre-VACUUM bloat
        #      that the operator would otherwise see between the weekly
        #      cron and the next container restart.
        #
        # The WAL file gets its own gauge because a large WAL is a
        # distinct failure mode from a large body — usually it means
        # checkpointing is stalled, not that the working set has grown.
        # Splitting the gauges lets the operator (and the alert rules in
        # ``docs/sre/prometheus_rules.yaml`` group ``ecm_database_size``)
        # distinguish the two without recomputing a derived series.
        #
        # SLO entry: capacity-planning class in ``docs/sre/slos.md``.
        # Runbook: ``docs/runbooks/database-size-warn.md``.
        # ----------------------------------------------------------------
        "database_size_bytes": Gauge(
            "ecm_database_size_bytes",
            "Size in bytes of the SQLite database file (``journal.db``). "
            "Updated post-VACUUM at startup (database._perform_maintenance) "
            "and after the weekly cleanup task (CleanupTask.execute). No "
            "labels — single-file, single-tenant.",
            registry=registry,
        ),
        "database_wal_size_bytes": Gauge(
            "ecm_database_wal_size_bytes",
            "Size in bytes of the SQLite WAL file (``journal.db-wal``). A "
            "large WAL relative to the body usually means checkpointing "
            "is stalled, not that the working set has grown — see the "
            "``database-size-warn`` runbook for the WAL-vs-body triage.",
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Auto-creation pre-run snapshot growth (ADR-010 §D7, uc51o.3).
        #
        # A per-run snapshot of ~570 channels serializes to roughly
        # 50 KB–3 MB, captured on every execute (incl. hourly
        # run_on_refresh). Retention (CleanupTask age window + count cap)
        # bounds it by construction; these two gauges make the current
        # state observable so an operator (and any future alert rule) can
        # see whether the cap is doing its job. Both are label-free —
        # single-file, single-tenant — matching the database-size gauges.
        #
        # ``snapshot_count`` is the live row count of auto_creation_snapshots;
        # the count cap (auto_creation_snapshot_max, default 50) is the
        # ceiling, so a value pinned at the cap means the prune is the
        # binding constraint (healthy). ``snapshot_bytes`` sums the
        # serialized channels_data payload (LENGTH(channels_data)) — the
        # storage cost — computed cheaply at prune time. Updated by
        # CleanupTask.execute after the snapshot prune. No established
        # alert rule yet; SRE owns the threshold (note in ADR-010 §D7).
        # ----------------------------------------------------------------
        "auto_creation_snapshot_count": Gauge(
            "ecm_auto_creation_snapshot_count",
            "Current number of auto_creation_snapshots rows retained. Bounded "
            "by the auto_creation_snapshot_max count cap (default 50) and the "
            "auto_creation_snapshot_days age window (default 30) enforced by "
            "CleanupTask. Updated after the snapshot prune. No labels.",
            registry=registry,
        ),
        "auto_creation_snapshot_bytes": Gauge(
            "ecm_auto_creation_snapshot_bytes",
            "Total size in bytes of the serialized channels_data payloads "
            "across all retained auto_creation_snapshots (SUM(LENGTH("
            "channels_data))). The storage cost of the snapshot table; the "
            "count cap holds this to a bounded ceiling. Updated after the "
            "snapshot prune. No labels.",
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Task scheduler health (bd-qxi02, bd-p5b8i SRE recommendation).
        #
        # Two gauges expose the operational health of the task scheduler
        # subsystem — the gap that allowed bd-p5b8i to go undetected for
        # 39+ days on the PO's install (4 months across all operators)
        # because the existing ecm_telemetry_rollup_last_success_timestamp
        # gauge fired only for rollup-specific tasks, no alert rule wired
        # it up, and no Prometheus deployment consumed the signal.
        #
        # ``task_schedule_last_success_timestamp`` labels by ``task_id`` —
        # a bounded enum drawn from the task_registry (~15 tasks defined
        # in code as task_class.task_id constants, PLUS one dynamically
        # registered ``dbas_sync_<sync_target_id>`` per SyncTarget row —
        # 7ipq2.3 / ADR-013 S6. The sync family is operator-created but
        # tightly bounded: a self-hosted install has 1-3 sync targets,
        # and ids come from code-controlled registration keyed on DB
        # pks, never raw user input). Updated by the task_engine on
        # every successful task execution to the current Unix epoch
        # seconds. Per-task so SRE staleness alerts can distinguish a
        # stuck stats_v2_rollup from a stuck cleanup from a stuck
        # stream_probe — each has a different cadence and a different
        # acceptable staleness window — and, for sync, a stalled target
        # B2 from a healthy B1 (ECMSyncStalledTargetDrift evaluates per
        # target series).
        #
        # ``task_schedule_next_run_null_count`` is label-free — the count
        # of task_schedules rows where next_run_at IS NULL AND enabled=1
        # AND schedule_type != 'manual'. Any non-zero value is the
        # canonical "scheduler subsystem is broken" signal — the exact
        # symptom bd-p5b8i exhibited (every non-MANUAL schedule had NULL
        # next_run_at, so the scheduler loop never picked them up). The
        # gauge is emitted at startup (post-Alembic) AND on every
        # ``sync_from_database`` so a heal during Bundle H's bd-p5b8i
        # remediation is visible on the next scrape.
        # ----------------------------------------------------------------
        "task_schedule_last_success_timestamp": Gauge(
            "ecm_task_schedule_last_success_timestamp",
            "Unix-epoch seconds of the most recent SUCCESSFUL execution "
            "of each scheduled task, labeled by task_id. Updated by the "
            "task_engine post-execution when the TaskResult is success. "
            "Per-task so SRE staleness alerts can distinguish a stuck "
            "stats_v2_rollup (25h budget) from a stuck cleanup (8d "
            "weekly) from a stuck stream_probe (48h, runs twice daily). "
            "Label cardinality is bounded by the task_registry — task_id "
            "values are code constants, not user-derived input.",
            ["task_id"],
            registry=registry,
        ),
        "task_schedule_next_run_null_count": Gauge(
            "ecm_task_schedule_next_run_null_count",
            "Count of task_schedules rows where next_run_at IS NULL AND "
            "enabled=1 AND schedule_type != 'manual'. Any non-zero value "
            "is the canonical 'scheduler subsystem is broken' signal — "
            "non-MANUAL enabled schedules MUST have a computed next_run_at "
            "for the scheduler loop to pick them up. Emitted at startup "
            "post-Alembic (database.init_db) AND on every TaskRegistry "
            "sync_from_database so Bundle H's heal is visible on the "
            "next scrape without waiting for a container restart.",
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Dedup candidate lookup latency (ADR-008 §D1 + BD-M locked contract).
        #
        # ``dedup_candidate_lookup_duration_seconds`` is the BD-M SLO-10
        # latency SLI for the interactive stream deduplication feature
        # (bd-1v4ht). Emitted by ``GET /api/channel-merges/candidates``
        # on every request, wrapping the ``find_candidate`` matcher call
        # (the latency bottleneck per ADR-008 §D9).
        #
        # Metric name is LOCKED CONTRACT per BD-M — do not rename without
        # updating BD-M's Prometheus alert rules (bd-ft3hk) in lockstep.
        # Buckets align with the drag-drop p95 < 200ms budget from the
        # epic body — the sub-100ms buckets cover the happy path (warm
        # Dispatcharr + small candidate set), the 500ms-2s tail covers
        # slow/cold Dispatcharr responses, and the 5s/10s buckets capture
        # the pathological case for SRE alerting.
        #
        # No labels — the endpoint has no label-safe bounded dimension
        # (group_id is user-supplied and unbounded as a label). Per-group
        # latency breakdown belongs in logs (trace_id correlation), not in
        # metric label space (SRE cardinality posture).
        # ----------------------------------------------------------------
        "dedup_candidate_lookup_duration_seconds": Histogram(
            "ecm_dedup_candidate_lookup_duration_seconds",
            "Duration of the find_candidate matcher call inside "
            "GET /api/channel-merges/candidates, in seconds. "
            "SLO-10 latency SLI for the interactive dedup feature "
            "(ADR-008 §D1, bd-ft3hk BD-M locked contract). "
            "No labels — group_id is unbounded cardinality.",
            buckets=_HTTP_LATENCY_BUCKETS,
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Interactive stream-dedup merge outcome (ADR-008, bd-ft3hk /
        # BD-M contract; emitted by BD-E's accept/dismiss endpoints).
        #
        # ``dedup_merge_requests_total`` labels by ``status`` — a bounded
        # enum drawn from ADR-008 §D6 outcome semantics:
        #   * ``success`` — accept completed end-to-end (SLO-10c denominator).
        #   * ``error``   — accept raised an unhandled exception or a
        #                   Dispatcharr 5xx (SLO-10c numerator). Excludes
        #                   4xx-by-design (404 stale target, 409 invalid
        #                   state) — those are correct backend behavior
        #                   per the bd-ct9wl / bd-ozhkf precedent and are
        #                   NOT service unreliability.
        #   * ``dismissed`` — operator (or MCP) chose to reject the
        #                   candidate. Not an error; counts toward
        #                   SLI-10b resolution (terminal state).
        #   * ``cancelled`` — reserved for the modal-cancel surface
        #                   (BD-G) when the operator opens the prompt and
        #                   then dismisses without choosing accept/reject.
        #                   BD-E does not emit this label itself.
        #   * ``unapplied`` — accept succeeded and ECM could NOT apply it
        #                   upstream, so the queue row deliberately stays
        #                   ``pending``, flagged and retryable (bead
        #                   enhancedchannelmanager-i5ic0, PO decision
        #                   2026-08-16). NOT a resolution: SLI-10b's
        #                   numerator is terminal-state transitions out of
        #                   the queue, and this makes none, so counting it
        #                   as ``success`` would have shown the queue being
        #                   cleared while flagged rows accumulated and
        #                   suppressed ECMDedupPendingMergeResolutionStale.
        #                   Not dropped either: the request happened, and
        #                   omitting it shrinks SLI-10c's DENOMINATOR.
        #
        # Label cardinality is hard-bounded to those five values per the
        # runbook contract (docs/runbooks/dedup-merge-api-error-rate-high.md),
        # which along with docs/sre/slos.md enumerates them and needs the
        # fifth added.
        #
        # The SLI-10b denominator counter
        # ``pending_merges_queue_depth_added_total`` is declared earlier
        # in this function (in the BD-F block) — owned by the enqueue
        # surface (currently bulk-M3U-import). BD-E does NOT emit it;
        # accept/dismiss transition the row's status, they do not INSERT.
        # ----------------------------------------------------------------
        "dedup_merge_requests_total": Counter(
            "ecm_dedup_merge_requests_total",
            "Count of POST /api/channel-merges/{id}/accept and /dismiss "
            "outcomes, labeled by status (success|error|dismissed|"
            "cancelled|unapplied). SLI-10c numerator (status='error') and "
            "SLI-10b numerator (status='success'|'dismissed' = terminal-state "
            "transitions out of the pending queue; 'unapplied' is NOT one, "
            "the row stays queued). 4xx-by-design "
            "responses (404 stale target, 409 invalid state) are NOT "
            "counted as 'error' per the bd-ct9wl / bd-ozhkf precedent.",
            ["status"],
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # Media-session attribution observability (bd-r5f0c.6).
        #
        # Six metrics cover the cache + resolver hot path for Emby /
        # Plex / Jellyfin user attribution. All share a single bounded
        # ``source`` label.
        #
        # Resolver metrics carry exactly three values: "emby", "plex",
        # "jellyfin" — one per primary attribution source.
        #
        # Cache metrics carry the resolver three values PLUS one
        # secondary surface introduced by bd-ma6r3:
        #
        #   * "plex_epg" — the Plex EPG-airings cache used by the
        #     :mod:`services.plex_epg_cache` module to cross-reference
        #     a Live TV session's ``grandparentTitle`` (program name)
        #     to the airing's ``channelCallSign``. The cache lives
        #     beside the session cache; same TTL / lock / stale-
        #     fallback envelope, different upstream surface and
        #     longer TTL (30 s vs 5 s session). Dashboards that filter
        #     on ``source=plex`` will see ONLY the session cache —
        #     filter on ``source=~"plex|plex_epg"`` for full Plex
        #     attribution-stack visibility.
        #
        # Attribution is best-effort (SLO-8 posture) — the alert rules
        # that wire on these are warn-only, never paging.
        #
        # Cache metrics (incremented by services/<source>_cache.py):
        #
        #   * ``media_session_cache_hits_total`` — cache hit before any
        #     upstream call (fast-path and under-lock re-check). One
        #     increment per cache-hit return, not per caller if multiple
        #     waiters share a just-populated entry.
        #   * ``media_session_fetch_duration_seconds`` — wall time of
        #     the upstream ``get_sessions()`` HTTP call. Cache hits are
        #     NOT counted — the histogram tracks upstream latency only.
        #     Buckets match ``_HTTP_LATENCY_BUCKETS`` (LAN requests, the
        #     same regime as other ECM upstream calls).
        #   * ``media_session_fetch_errors_total`` — upstream fetch raised
        #     an exception (network error, auth failure, server error).
        #     The stale-fallback and cold-start paths both increment this
        #     counter so the denominator is "all failed fetch attempts",
        #     not just the ones that had a stale entry to fall back on.
        #   * ``media_session_stale_fallback_total`` — stale cache entry
        #     returned after a fetch failure. Subset of fetch_errors_total
        #     (only those where a prior cache existed). Non-zero rate means
        #     ECM is serving stale data to the resolver.
        #
        # Resolver metrics (incremented by services/<source>_resolver.py):
        #
        #   * ``user_attribution_resolved_total`` — resolver matched a
        #     session to a user (returned a non-None attribution).
        #     Incremented AFTER the IP match succeeds and a session match
        #     is found — the IP short-circuit (not our session) does NOT
        #     increment this counter.
        #   * ``user_attribution_unresolved_total`` — resolver had an IP
        #     match (the session came from the right source server) but
        #     found no matching Emby/Plex/Jellyfin session. Incremented
        #     after the IP-match succeeds and the session match loop
        #     returns empty. The IP short-circuit does NOT increment.
        #
        # The ratio resolved / (resolved + unresolved) is the attribution
        # quality SLI for the r5f0c epic — target ≥ 80% steady state
        # (operators who configure all three sources should see most
        # sessions attributed). Below 50% for > 30m → investigate.
        # ----------------------------------------------------------------
        "media_session_cache_hits_total": Counter(
            "ecm_media_session_cache_hits_total",
            "Count of per-source session-cache hits (returned without an "
            "upstream fetch). source ∈ {emby, plex, jellyfin, plex_epg}. "
            "Incremented on both the fast-path hit (before lock) and the "
            "under-lock re-check hit (another waiter populated the cache "
            "while we waited). Does NOT count cache misses that went to "
            "the upstream and succeeded. The plex_epg label (bd-ma6r3) "
            "covers the Plex EPG-airings cache, a secondary surface used "
            "only by the Plex resolver's Live TV cross-reference tier.",
            ["source"],
            registry=registry,
        ),
        "media_session_fetch_duration_seconds": Histogram(
            "ecm_media_session_fetch_duration_seconds",
            "Wall time of the upstream get_sessions() HTTP call, in "
            "seconds. source ∈ {emby, plex, jellyfin, plex_epg}. Cache "
            "hits are NOT counted — this histogram tracks upstream "
            "latency only. Recorded on every fetch attempt regardless "
            "of outcome (success or exception); the _count gives total "
            "fetch attempts, the _sum gives total latency across all "
            "fetches. The plex_epg label (bd-ma6r3) measures the full "
            "DVR/section sweep (multiple sequential HTTP GETs); samples "
            "will be wider than the single-GET session caches.",
            ["source"],
            buckets=_HTTP_LATENCY_BUCKETS,
            registry=registry,
        ),
        "media_session_fetch_errors_total": Counter(
            "ecm_media_session_fetch_errors_total",
            "Count of upstream session-fetch failures (exception raised "
            "by the upstream client). source ∈ {emby, plex, jellyfin, "
            "plex_epg}. Incremented on every exception from "
            "get_sessions() / get_current_live_epg_channels(), "
            "regardless of whether a stale cache exists to fall back on. "
            "Alert rule MediaSessionFetchErrorsSustained fires when this "
            "counter has a non-zero rate for > 10m (warn-only, SLO-8 "
            "posture — attribution is best-effort).",
            ["source"],
            registry=registry,
        ),
        "media_session_stale_fallback_total": Counter(
            "ecm_media_session_stale_fallback_total",
            "Count of stale-cache returns after an upstream fetch failure. "
            "source ∈ {emby, plex, jellyfin, plex_epg}. Incremented when "
            "fetch_errors_total fires AND a prior cache entry exists to "
            "return. A non-zero rate means ECM is serving stale session "
            "data to resolvers; attribution quality degrades but does not "
            "go dark (the stale entry is still returned). Alert rule "
            "MediaSessionStaleFallbackRising fires when rate > 0.01 for "
            "> 30m (warn-only, SLO-8 posture).",
            ["source"],
            registry=registry,
        ),
        "user_attribution_resolved_total": Counter(
            "ecm_user_attribution_resolved_total",
            "Count of successful user-attribution resolutions per source. "
            "source ∈ {emby, plex, jellyfin}. Incremented by the "
            "resolver when the ECM session IP matches the source server IP "
            "AND a session match is found across the three match tiers. "
            "The IP-short-circuit case (session is not from this source's "
            "server) is NOT counted. Numerator of the attribution quality "
            "SLI: resolved / (resolved + unresolved).",
            ["source"],
            registry=registry,
        ),
        "user_attribution_unresolved_total": Counter(
            "ecm_user_attribution_unresolved_total",
            "Count of attribution failures for sessions whose IP matched "
            "the source server but no session match was found. "
            "source ∈ {emby, plex, jellyfin}. Incremented when the IP "
            "matches the configured source server but the three-tier "
            "session-match loop returns empty. Does NOT increment on "
            "IP-short-circuit (session is not from this source). "
            "Denominator complement: resolved / (resolved + unresolved) "
            "is the attribution quality SLI.",
            ["source"],
            registry=registry,
        ),
        # ----------------------------------------------------------------
        # SLO-8 dashboard signal — Unknown-bucket channel count (bd-w89ox)
        #
        # Incremented once per /api/stats/channels response for EACH channel
        # whose m3u_account_id is None after the live stream-identity resolver
        # runs. A non-zero rate indicates that some active channels cannot be
        # attributed to an M3U provider — the "Unknown" bucket in the Providers
        # panel. This counter lets SRE build ratio panels against the total
        # active-channel count (ecm_http_requests_total is not suitable for
        # this ratio — use the Dispatcharr-reported channel count from
        # /api/stats/channels as the denominator in dashboards).
        #
        # Cardinality: label-free counter. One counter process-wide. No
        # per-channel, per-provider, or per-user labels — those belong in
        # structured logs ("[STATS] unknown_provider channel_id=... url=...").
        # ----------------------------------------------------------------
        "stats_active_channels_unknown_provider_total": Counter(
            "ecm_stats_active_channels_unknown_provider_total",
            "Count of /api/stats/channels response entries where "
            "m3u_account_id is None (provider attribution could not be "
            "resolved for the active stream). Incremented once per "
            "unattributed channel per /api/stats/channels call. "
            "Use as numerator against total active channels for the "
            "Unknown-bucket rate on SLO-8 dashboards. bd-w89ox.",
            registry=registry,
        ),
    }


def install_metrics(registry: Optional[CollectorRegistry] = None) -> Dict[str, Any]:
    """Create the metric set on ``registry`` (or a fresh registry).

    Returns the populated ``_METRICS`` dict. Subsequent calls reuse the
    existing registry — the registry is process-global because Prometheus
    clients collate samples from it at scrape time.
    """
    global REGISTRY, _METRICS
    if REGISTRY is None:
        REGISTRY = registry or CollectorRegistry()
        _METRICS = _build_metrics(REGISTRY)
        _publish_app_info()
    return _METRICS


def _publish_app_info() -> None:
    """Stamp the build-identity labels onto ``ecm_app_info`` (bd-h0wfu).

    Reads the same env vars that ``/api/health`` and ``/api/version`` echo
    so operators see the same SHA in three places — Prometheus, the JSON
    health probe, and the dedicated version endpoint. All three are
    populated from Dockerfile build ARGs, so a fresh image build mints a
    new (version, git_sha) time series and stale containers are
    immediately distinguishable from the running ``origin/dev`` HEAD.

    Defensive: never raises. If prometheus-client is missing or the env
    vars are absent, the gauge is simply not stamped — better than taking
    down app startup over an observability nicety.
    """
    if not _METRICS:
        return
    try:
        gauge = _METRICS.get("app_info")
        if gauge is None:
            return
        version = os.environ.get("ECM_VERSION", "unknown")
        git_sha = os.environ.get("GIT_COMMIT", "unknown")
        release_channel = os.environ.get("RELEASE_CHANNEL", "latest")
        gauge.labels(
            version=version,
            git_sha=git_sha,
            release_channel=release_channel,
        ).set(1.0)
    except Exception:  # pragma: no cover — observability must not break startup
        logging.getLogger(__name__).debug(
            "[OBSERVABILITY] Failed to publish ecm_app_info gauge", exc_info=True
        )


def get_metric(name: str) -> Any:
    """Return the metric object registered under ``name`` (e.g. ``"http_requests_total"``)."""
    if not _METRICS:
        install_metrics()
    return _METRICS[name]


def set_pending_merges_queue_depth_gauge(db) -> None:
    """Read the current pending_merges queue depth and update the gauge.

    Queries ``SELECT COUNT(*) FROM pending_merges WHERE status='pending'``
    via the supplied SQLAlchemy session and calls
    ``ecm_pending_merges_queue_depth.set(count)``.

    This helper is the single canonical implementation shared by all four
    call sites that change the pending_merges queue depth:

      * BD-F insert (``backend/services/m3u_dedup_hook.py``)
      * BD-E accept  (``backend/routers/channel_merges.py``)
      * BD-E dismiss (``backend/routers/channel_merges.py``)
      * App startup  (``backend/main.py``)

    The helper is intentionally best-effort: a failed COUNT or gauge-set
    is logged at WARN with the ``[DEDUP]`` prefix and swallowed — gauge
    accuracy is a diagnostic nicety, NOT a correctness requirement. The
    caller's queue-state transition (insert / status flip / startup seed)
    is never blocked by an observability failure.

    Parameters
    ----------
    db:
        An active SQLAlchemy ``Session`` that is already connected to the
        ECM journal DB. The COUNT query is read-only and does NOT consume
        a transaction slot or flush any pending state.
    """
    try:
        from sqlalchemy import text as _sa_text
        row = db.execute(_sa_text("SELECT COUNT(*) FROM pending_merges WHERE status='pending'")).fetchone()
        count = row[0] if row is not None else 0
        get_metric("pending_merges_queue_depth").set(float(count))
    except Exception:  # pragma: no cover — gauge set is best-effort, never blocks callers
        logging.getLogger(__name__).warning(
            "[DEDUP] set_pending_merges_queue_depth_gauge: COUNT query or "
            "gauge.set failed — gauge may be stale",
            exc_info=True,
        )


def update_database_size_metrics(db_path: Optional[str] = None) -> None:
    """Sample the SQLite DB and WAL file sizes onto the gauges (bd-ygoqr).

    Called from the two points that already do real DB I/O:

    * ``database._perform_maintenance`` — at process startup, post-VACUUM.
    * ``tasks.cleanup.CleanupTask.execute`` — after the weekly VACUUM.

    Cost is two ``os.path.getsize`` calls (single syscall each). The body
    gauge is set to 0 when the file is missing (e.g., a fresh install
    where ``journal.db`` was created mid-call); the WAL gauge stays at 0
    when the WAL has been checkpointed away (the steady state on a
    healthy install).

    Defensive: never raises. Observability instrumentation must not break
    the maintenance code path it's wrapping. A failure to publish is logged
    at DEBUG.

    Parameters
    ----------
    db_path:
        Absolute path to the SQLite DB file. When ``None``, resolves to
        ``database.JOURNAL_DB_FILE`` lazily (the import is inside the
        function so tests that haven't initialized the DB module don't
        pay an import-time cost).
    """
    try:
        if db_path is None:
            from database import JOURNAL_DB_FILE  # local to avoid import cycle
            db_path = str(JOURNAL_DB_FILE)

        body_size = 0
        if os.path.exists(db_path):
            body_size = os.path.getsize(db_path)
        get_metric("database_size_bytes").set(float(body_size))

        wal_path = db_path + "-wal"
        wal_size = 0
        if os.path.exists(wal_path):
            wal_size = os.path.getsize(wal_path)
        get_metric("database_wal_size_bytes").set(float(wal_size))
    except Exception:  # pragma: no cover — never break the caller
        logging.getLogger(__name__).debug(
            "[OBSERVABILITY] update_database_size_metrics failed", exc_info=True
        )


def update_auto_creation_snapshot_metrics(session=None) -> None:
    """Sample the auto_creation_snapshots count + size onto the gauges (ADR-010 §D7).

    Publishes ``ecm_auto_creation_snapshot_count`` (live row count) and
    ``ecm_auto_creation_snapshot_bytes`` (SUM(LENGTH(channels_data)) — the
    serialized payload size, computed without parsing the BLOB) so the
    growth of the pre-run snapshot table is observable and the count cap's
    effectiveness is visible.

    Called from ``tasks.cleanup.CleanupTask.execute`` immediately after the
    snapshot prune step, so the gauges reflect the post-prune state.

    Defensive: never raises. Observability instrumentation must not break the
    cleanup task it's wrapping. A failure to publish is logged at DEBUG.

    Parameters
    ----------
    session:
        An active SQLAlchemy ``Session`` already connected to the journal DB
        (the cleanup task passes its own). When ``None``, opens a fresh
        session via ``database.get_session`` (the import is local so tests
        that haven't initialized the DB module don't pay an import-time cost).
    """
    own_session = False
    try:
        from sqlalchemy import func

        from models import ChannelPipelineSnapshot

        if session is None:
            from database import get_session  # local — avoid import cycle
            session = get_session()
            own_session = True

        count = session.query(func.count(ChannelPipelineSnapshot.id)).scalar() or 0
        total_bytes = session.query(
            func.coalesce(func.sum(func.length(ChannelPipelineSnapshot.channels_data)), 0)
        ).scalar() or 0

        get_metric("auto_creation_snapshot_count").set(float(count))
        get_metric("auto_creation_snapshot_bytes").set(float(total_bytes))
    except Exception:  # pragma: no cover — never break the caller
        logging.getLogger(__name__).debug(
            "[OBSERVABILITY] update_auto_creation_snapshot_metrics failed",
            exc_info=True,
        )
    finally:
        if own_session and session is not None:
            session.close()


def record_task_success(task_id: str, timestamp: Optional[float] = None) -> None:
    """Stamp the ``ecm_task_schedule_last_success_timestamp`` gauge for a task.

    Called by ``task_engine._execute_task`` immediately after a task's
    ``TaskResult`` reports ``success=True`` and ``error != "CANCELLED"``.
    The gauge is the SLI surface for the per-task staleness alerts in
    the ``ecm_task_scheduler`` Prometheus rules group — without this
    update, those alerts cannot distinguish "task hasn't been scheduled
    in days" (the bd-p5b8i failure mode) from "task is healthy and
    polling normally."

    Defensive: never raises. Observability instrumentation must not
    take down the task execution path it's wrapping. A failure to
    publish is logged at DEBUG.

    Parameters
    ----------
    task_id:
        The task registry key (e.g. ``"stats_v2_rollup"``,
        ``"cleanup"``, ``"stream_probe"``). Must be a code constant
        from the task_registry — not user-derived input. Label
        cardinality is bounded by the registry, not by request shape.
    timestamp:
        Override for the Unix-epoch timestamp value. Defaults to
        ``time.time()`` (current wall-clock). Exposed for tests so
        they can pin the value without mocking ``time.time``.
    """
    try:
        if timestamp is None:
            timestamp = time.time()
        get_metric("task_schedule_last_success_timestamp").labels(
            task_id=task_id
        ).set(float(timestamp))
    except Exception:  # pragma: no cover — observability must not break task engine
        logging.getLogger(__name__).debug(
            "[OBSERVABILITY] record_task_success failed for task_id=%s",
            task_id, exc_info=True,
        )


def record_sync_full_success(
    sync_target_id: int, timestamp: Optional[float] = None
) -> None:
    """Stamp ``ecm_sync_last_full_success_timestamp`` for one sync target.

    Called by ``tasks.dbas_sync.DbasSyncTask`` ONLY when a run actually
    APPLIED (``confirm_apply=True``) and the ``RestoreReport`` outcome was a
    clean ``SUCCESS``. Dry-run previews, partial/rolled-back applies, and
    credential-freshness aborts must NOT call this — the whole point of the
    dedicated gauge is that it means "B was fully converged at time T",
    which the generic per-task success gauge cannot express (the task engine
    stamps that one on any success, preview included; PR #752 review Block 2).

    Defensive: never raises. Observability must not break the sync path.

    Parameters
    ----------
    sync_target_id:
        The ``SyncTarget`` row pk. Rendered as the string label value;
        cardinality is bounded by the operator's sync_targets rows.
    timestamp:
        Override for the Unix-epoch value. Defaults to ``time.time()``.
        Exposed for tests so they can pin the value.
    """
    try:
        if timestamp is None:
            timestamp = time.time()
        get_metric("sync_last_full_success_timestamp").labels(
            sync_target_id=str(sync_target_id)
        ).set(float(timestamp))
    except Exception:  # pragma: no cover — must not break the sync path
        logging.getLogger(__name__).debug(
            "[OBSERVABILITY] record_sync_full_success failed for target=%s",
            sync_target_id, exc_info=True,
        )


def update_task_schedule_null_count(count: Optional[int] = None) -> None:
    """Set the ``ecm_task_schedule_next_run_null_count`` gauge.

    Counts ``task_schedules`` rows where ``next_run_at IS NULL AND
    enabled=1 AND schedule_type != 'manual'`` — any non-zero value is
    the canonical "scheduler subsystem is broken" signal (bd-p5b8i).

    Called from:

    * ``database.init_db`` post-``_run_migrations`` — establishes the
      startup value before Bundle H's heal can change it, so SRE sees
      the pre-heal count in the boot trace.
    * ``task_registry.TaskRegistry.sync_from_database`` — re-emitted
      after the registry has finished its own bookkeeping so a heal
      that ran during sync_from_database is reflected immediately.
    * ``task_engine.TaskEngine._scheduler_loop`` — invoked on every
      scheduler tick (default cadence ~60s, matches
      ``TaskEngine.check_interval``) so the gauge has per-scrape
      freshness for the 5m alert window in ``prometheus_rules.yaml``.
      Without this third call site the gauge would only refresh at
      boot, which means a mid-life regression that caused
      ``next_run_at`` to drift to NULL would not be detected until
      the next container restart. The COUNT(*) query is cheap (one
      indexed lookup against task_schedules, ~10 rows in practice).

    Defensive: never raises. When ``count`` is ``None``, queries the
    DB lazily — the import is inside the function so tests that
    haven't initialized the DB module don't pay an import-time cost.
    A query failure (DB unreachable, table missing on a fresh install)
    leaves the gauge untouched and logs at DEBUG. The caller can pass
    ``count`` directly to avoid the implicit query (e.g., when the
    caller already has a live session open).

    Parameters
    ----------
    count:
        When provided, the gauge is set to ``float(count)`` directly.
        When ``None``, the function opens a fresh session via
        ``database.get_session`` and runs the count query itself.
    """
    try:
        if count is None:
            from sqlalchemy import text  # local — keep observability importable without sqlalchemy
            from database import get_session
            session = get_session()
            try:
                row = session.execute(text(
                    "SELECT COUNT(*) FROM task_schedules "
                    "WHERE next_run_at IS NULL "
                    "AND enabled = 1 "
                    "AND schedule_type != 'manual'"
                )).fetchone()
                count = int(row[0]) if row and row[0] is not None else 0
            finally:
                session.close()
        get_metric("task_schedule_next_run_null_count").set(float(count))
    except Exception:  # pragma: no cover — observability must not break startup or scheduler
        logging.getLogger(__name__).debug(
            "[OBSERVABILITY] update_task_schedule_null_count failed", exc_info=True
        )


def render_metrics() -> bytes:
    """Return the Prometheus text-format exposition of the current registry."""
    if REGISTRY is None:
        install_metrics()
    return generate_latest(REGISTRY)


def reset_for_tests() -> None:
    """Drop the current registry — used by tests that rebuild it per case."""
    global REGISTRY, _METRICS
    REGISTRY = None
    _METRICS = {}
    reset_normalization_sampler_for_tests()


# =========================================================================
# Normalization decision log (bd-eio04.9)
# =========================================================================
# Structured INFO log for every (sampled) normalization decision. The
# decision log supplements the metrics in `_build_metrics` — metrics
# answer "how often" and "how fast", the log answers "which input, which
# rules, what did it produce?". The two together give on-call a
# 2-minute path from "SLO-5 burning" → "exactly which fixture diverged".
#
# Volume control:
#   * Baseline stride sampler — default every 10th call (10%).
#   * Always-sample when the decision is "we changed something": applied
#     is True AND matched_rule_ids is non-empty. Bug-hunting only cares
#     about decisions that acted; "ran and did nothing" traffic is what
#     the stride sampler keeps bounded.
#   * PO decision (grooming 2026-04-22): deterministic every-N stride,
#     not random sampling, so the same traffic produces the same log
#     content across replays (helps canary failure forensics).
#
# Truncation + hashing:
#   * `input` and `output` fields are truncated to 256 chars (they can
#     be arbitrarily long user content). Truncation marker: trailing
#     "...[truncated]" sentinel.
#   * `input_sha256` is ALWAYS included — the full hash of the raw input
#     — so on-call can correlate across log lines when the truncation
#     strips the distinguishing tail.

NORMALIZATION_DECISION_LOGGER = "ecm.normalization.decision"
_DECISION_FIELD_MAX_CHARS = 256
_DECISION_TRUNCATION_SENTINEL = "...[truncated]"

# Default stride: emit one INFO log per N calls. 10 = 10% baseline. This
# default tracks the SRE dashboard budget noted in the bead — at peak
# auto-creation traffic, a 10% baseline combined with "always on
# applied=true" caps log volume at roughly one line per rule match plus
# a sample of the no-op traffic.
_DEFAULT_SAMPLE_STRIDE = 10

# Bounded enum of rule categories used as the `rule_category` metric
# label. Keys are NormalizationRule.action_type values seen in the
# codebase (see backend/normalization_engine.py::_apply_action). Anything
# outside this enum is mapped to "other" by `_normalize_rule_category`
# so the label cardinality is bounded regardless of future rule types.
_KNOWN_RULE_CATEGORIES = frozenset({
    "remove",
    "replace",
    "regex_replace",
    "strip_prefix",
    "strip_suffix",
    "normalize_prefix",
    "capitalize",
    "tag_group",
    "legacy_tag",
})


def _normalize_rule_category(raw: Optional[str]) -> str:
    """Map a raw rule action_type onto the bounded metric-label enum.

    Unknown / empty values collapse to ``"other"`` so the Prometheus
    label stays bounded regardless of what the caller passes.
    """
    if not raw:
        return "other"
    normalized = str(raw).strip().lower()
    if normalized in _KNOWN_RULE_CATEGORIES:
        return normalized
    return "other"


class _DeterministicSampler:
    """Every-N stride sampler for structured decision logs.

    Sampling rule (bd-eio04.9):
        * If ``always_keep`` is True (caller knows this decision
          actually changed the string) — always emit.
        * Otherwise emit one out of every ``stride`` calls. Stride is
          applied deterministically against a monotonically-increasing
          counter, so replaying the same traffic twice produces the
          same sampled subset.

    Thread-safe: ``threading.Lock`` guards the counter because the
    auto-creation executor runs on multiple workers. Locking a single
    integer increment is ~200ns — negligible next to the normalization
    work itself.
    """

    def __init__(self, stride: int = _DEFAULT_SAMPLE_STRIDE) -> None:
        self._stride = max(1, int(stride))
        self._counter = 0
        self._lock = threading.Lock()

    @property
    def stride(self) -> int:
        return self._stride

    def set_stride(self, stride: int) -> None:
        """Update the stride. Resets the counter to 0 so the next call is kept."""
        with self._lock:
            self._stride = max(1, int(stride))
            self._counter = 0

    def should_sample(self, always_keep: bool = False) -> bool:
        """Return True when this call should be emitted as INFO."""
        if always_keep:
            # Advance the counter anyway so "always-keep" traffic does
            # not desynchronize the stride sampler for the baseline
            # path. Otherwise a burst of applied decisions would make
            # the next no-op decision look like a "fresh" cycle start.
            with self._lock:
                self._counter += 1
            return True
        with self._lock:
            self._counter += 1
            # Emit when counter hits 1, stride+1, 2*stride+1, … so the
            # very first call is always logged (helps smoke-testing
            # that the hook is wired up).
            return (self._counter - 1) % self._stride == 0


def _read_stride_from_env() -> int:
    """Read the sampler stride from ECM_NORMALIZATION_LOG_STRIDE.

    Invalid / non-integer values fall back to the default stride. Zero
    or negative values are clamped to 1 (emit every call) — useful for
    debugging, never the default.
    """
    raw = os.environ.get("ECM_NORMALIZATION_LOG_STRIDE")
    if not raw:
        return _DEFAULT_SAMPLE_STRIDE
    try:
        value = int(raw.strip())
    except (TypeError, ValueError):
        return _DEFAULT_SAMPLE_STRIDE
    return max(1, value)


_normalization_sampler = _DeterministicSampler(stride=_read_stride_from_env())


def get_normalization_sampler() -> _DeterministicSampler:
    """Return the process-wide normalization decision log sampler."""
    return _normalization_sampler


def reset_normalization_sampler_for_tests(stride: Optional[int] = None) -> None:
    """Reset the sampler to a clean state. ONLY for tests."""
    global _normalization_sampler
    _normalization_sampler = _DeterministicSampler(
        stride=stride if stride is not None else _read_stride_from_env()
    )


def _truncate_for_log(value: str, max_chars: int = _DECISION_FIELD_MAX_CHARS) -> str:
    """Truncate ``value`` to ``max_chars`` with a visible sentinel.

    Returns the original string when ``len(value) <= max_chars``. Otherwise
    trims to ``max_chars`` and appends ``...[truncated]`` so operators
    reading the log know the value was clipped.
    """
    if value is None:
        return ""
    s = str(value)
    if len(s) <= max_chars:
        return s
    return s[:max_chars] + _DECISION_TRUNCATION_SENTINEL


def sha256_of(value: str) -> str:
    """Return the hex SHA-256 of ``value`` encoded as UTF-8.

    Exposed as a helper so the canary harness (see
    ``scripts/normalization_canary.py``) can compute the same hash the
    decision log records without duplicating the logic.
    """
    if value is None:
        value = ""
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def record_normalization_decision(
    *,
    input_text: str,
    output_text: str,
    matched_rule_ids: Iterable[Any],
    applied: bool,
    policy_version: str,
    duration_seconds: Optional[float] = None,
    rule_category: Optional[str] = None,
    extra: Optional[Dict[str, Any]] = None,
    logger_name: str = NORMALIZATION_DECISION_LOGGER,
) -> bool:
    """Emit a sampled INFO-level decision log line.

    Always updates the metrics (no-change counter, duration histogram)
    regardless of whether the log line is emitted — metrics are cheap,
    the sampler only decides whether to write the log. This is the
    entry point used by ``normalization_engine.NormalizationEngine``
    and by the canary harness so the two paths feed the same
    observability sinks with byte-identical structure.

    Parameters
    ----------
    input_text:
        The raw input to normalize. Truncated to 256 chars in the log;
        hashed fully into ``input_sha256``.
    output_text:
        The normalized output. Truncated to 256 chars.
    matched_rule_ids:
        Iterable of rule identifiers that matched. Coerced to a list of
        ints or strings — whatever the caller already has.
    applied:
        True when the output changed relative to the input OR a rule
        matched. The sampler always keeps decisions where
        ``applied and matched_rule_ids`` — those are the bug-hunting
        signal. No-op traffic is throttled to the stride.
    policy_version:
        Identifier of the NormalizationPolicy build — e.g.
        ``"unified-v1"`` vs. ``"legacy"``. Flows into the log so SRE
        can correlate divergence with the policy flag.
    duration_seconds:
        Wall time of the normalize() call. When provided, observed
        into the duration histogram. Ignored when ``None`` (the caller
        didn't measure).
    rule_category:
        Optional coarse rule category for the metric label. Passed
        through ``_normalize_rule_category`` so unknown values map to
        ``"other"``.
    extra:
        Optional dict of additional structured fields for the log
        payload (e.g. ``{"source": "auto_create", "channel_id": 42}``).

    Returns
    -------
    bool
        True when the log line was actually emitted (i.e. the sampler
        kept this call). Callers generally don't need the return value;
        it's exposed for testing.
    """
    # Metrics are updated unconditionally — they're cheap and the
    # sampler only applies to logs.
    try:
        if duration_seconds is not None:
            get_metric("normalization_duration_seconds").observe(
                max(0.0, float(duration_seconds))
            )
        if not applied and not list(matched_rule_ids):
            # "Ran but did nothing" — counted separately so dashboards
            # can show the ratio of no-op normalize() calls.
            get_metric("normalization_no_change_total").inc()
        if rule_category:
            get_metric("normalization_rule_matches_total").labels(
                rule_category=_normalize_rule_category(rule_category)
            ).inc()
    except Exception:  # pragma: no cover — metrics must never break the pipeline
        # Observability must never take down the code path it's
        # instrumenting. Log at DEBUG so the failure is visible in
        # dev but never fatal.
        logging.getLogger(__name__).debug(
            "[NORMALIZE] metric update failed for decision log", exc_info=True
        )

    rule_ids_list = list(matched_rule_ids or [])
    always_keep = bool(applied and rule_ids_list)
    sampler = get_normalization_sampler()
    if not sampler.should_sample(always_keep=always_keep):
        return False

    payload: Dict[str, Any] = {
        "input": _truncate_for_log(input_text),
        "output": _truncate_for_log(output_text),
        "matched_rule_ids": rule_ids_list,
        "applied": bool(applied),
        "policy_version": policy_version,
        "input_sha256": sha256_of(input_text),
    }
    if rule_category:
        payload["rule_category"] = _normalize_rule_category(rule_category)
    if duration_seconds is not None:
        # Round to microseconds so the log stays compact; the histogram
        # keeps the raw distribution.
        payload["duration_seconds"] = round(float(duration_seconds), 6)
    if extra:
        for key, value in extra.items():
            # Don't let callers clobber reserved field names.
            if key not in payload:
                payload[key] = value

    # Use lazy %-formatting per the backend logging convention. Passing
    # the structured dict through `extra` surfaces it as individual
    # attributes on the LogRecord — the JsonFormatter flattens those
    # into the top-level JSON body automatically.
    logger = logging.getLogger(logger_name)
    logger.info(
        "[NORMALIZE] decision applied=%s rules=%s sha=%s",
        payload["applied"],
        rule_ids_list,
        payload["input_sha256"][:12],
        extra=payload,
    )
    return True


# =========================================================================
# Single entry point wired from main.py
# =========================================================================
def install_observability(level: int = logging.INFO) -> None:
    """Install JSON logging + the Prometheus metric set.

    Call exactly once during application startup. Safe to call multiple
    times — both sub-installers are idempotent.
    """
    install_json_logging(level=level)
    install_metrics()
